In [2]:
import pandas as pd
import numpy as np


Merge k (in this case k=2) arrays and sort them.

In [3]:
a1 = np.array([1,4,6,78,4,3,1,19])
a2 = np.array([2,7,5,2,66,1,0,10])


In [4]:
for i in a1:
    

array([ 3, 11, 11, 80, 70,  4,  1, 29])

In [3]:
a1

array([ 1,  4,  6, 78,  4,  3,  1, 19])

In [19]:

def sort_array(ar):
    ar.sort()
    return ar

In [20]:
 new = sort_array([1,1,12,3,4,5,6])

In [21]:
print(new)

[1, 1, 3, 4, 5, 6, 12]


### How do you find percentile? Write the code for it.



In [4]:
time = [0,2,4,6,8,10, 12]
ppl = [0, 350, 1100, 2400, 6500, 8500, 10000]

In [63]:
def return_index(ppl, percentile):
    threshold = ppl[-1]*percentile/100
    
    for x in range(len(ppl)):
        if ppl[x] >= threshold:
            d = threshold - ppl[x-1]
            r = ppl[x]- ppl[x-1]
            return x, x-1, d/r
        else:
            pass
            
def return_time(x, y, rate, time):
    r = (time[x] - time[y])
    z = time[y] + r*rate
    return z

def return_percentile(ppl, time, p):
    x, y, pr = return_index(ppl, p)
    value = return_time(x, y, pr, time)
    return value

In [62]:
print(return_percentile(ppl, time, 30))

4 3 0.14634146341463414 6.2926829268292686
6.2926829268292686


In [5]:
ppl[-1]

10000

In [6]:
# test case
t = [0,1,2,3,4,5]
ppl = [0, 1000, 2000, 3000, 4000, 5000]

In [14]:
def return_index_ppl(ppl, percentile):
    threshold = ppl[-1]*percentile/100
    
    for p in range(len(ppl)):
        if ppl[p] >= threshold:
            index_1 = p-1
            range_ = ppl[p] - ppl[index_1]
            difference = ppl[p] - threshold
            rate = difference/range_
            
            return p, index_1, rate
        else:
            pass

def return_t(t, x, y, rate):
    difference = t[x] - t[y]
    time = t[y] + rate*difference
    return time
            
def return_time(t, ppl, percentile):
    
    x, y, rate = return_index_ppl(ppl, percentile)
    time = return_t(t, x, y, rate)
    
    return time
    

In [15]:
percentile = 30
v = return_time(t, ppl, 30)
print(v)

1.5


### Matrix

In [69]:
b = [[1,2], [5,7]]

In [70]:
temp_mat = np.array(b)

In [75]:
temp_mat

array([[1, 2],
       [5, 7]])

In [77]:
for i in b:
    print(i)

[1, 2]
[5, 7]
